repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.18.0'
    hooks:
      - id: eslint
        additional_dependencies:
          - 'eslint@8.18.0'
          - '@typescript-eslint/eslint-plugin@5.10.0'
          - '@typescript-eslint/parser@5.10.0'
          - 'eslint-config-prettier@8.1.0'
          - 'eslint-plugin-vue@8.5.0'
        types_or: [vue, ts, javascript]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        types_or: [vue, ts, javascript, css, scss, html, json, yaml]

ci:
  autoupdate_branch: 'master'
